spring:
  application:
    name: logconsumer-service
  kafka:
    bootstrap-servers: localhost:9092
    auto-offset-reset: latest
    group-id: consumer-group
    topic:
      name: kafka-log-topic

  data:
    mongodb:
        host: localhost
        port: 27017
        database: error-logs
        username: admin
        password: example

server:
    port: 8084
