#server.port=9001


#spring.application.name=user-service-main
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}


server:
  port: '9001'
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: kafka-log-topic
  application:
    name: user-service-main
  main:
    allow-bean-definition-overriding: 'true'
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}