server:
  port: '9002'
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: kafka-log-topic
  application:
    name: order-service-main
  main:
    allow-bean-definition-overriding: 'true'
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}