server:
  port: '9003'
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: kafka-log-topic
  application:
    name: product-service-main
  main:
    allow-bean-definition-overriding: 'true'

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    queue:
      increase: increaseQueue
      decrease: decreaseQueue
    exchange: exchange
    routingkey:
      increase: increase
      decrease: decrease
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}